### ISSUE TITLE
Action cannot run on `pull_request_target`

### ISSUE THREAD

**Issue by forntoh** [budougumi0617/action-pr-size-checker#9]
I need to use pull_request_target because without it, the action is unable to post a comment on the pull request if the pull request comes from a fork of the repo.

I was using pull_request before but it doesn't work it fails with 403 not enough permissions when calling the api to post a comment.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/de91984b-7cf6-4a58-9a43-5116e735d059">

https://github.com/forntoh/LcdMenu/actions/runs/10900728873/job/30248984698?pr=202

**Comment by budougumi0617** [comment]
Thank you for using my tool, and I also appreciate the issue report 😄  I will address it within a couple of days!

**Comment by budougumi0617** [comment]
@forntoh I have released the new version v0.0.8. If it doesn’t meet your expectations, I would appreciate it if you could write another issue.


https://github.com/budougumi0617/action-pr-size-checker/releases/tag/v0.0.8

Best regards,
